# Generated by Django 6.0.4 on 2026-06-10 11:33

import Advisory_Opinions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Laws', '0011_alter_law_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryOpinion',
            fields=[
                ('id', models.CharField(default=Advisory_Opinions.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True)),
                ('base_content', models.TextField(blank=True, null=True)),
                ('main_content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=700, null=True)),
                ('main_source', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('scrape_source', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.BigIntegerField(default=0)),
                ('instructions_json', models.JSONField(blank=True, null=True)),
                ('unificationRulingsACJ_json', models.JSONField(blank=True, null=True)),
                ('judicial_sessions_json', models.JSONField(blank=True, null=True)),
                ('regulations_json', models.JSONField(blank=True, null=True)),
                ('general_assembly_decisions_acj_json', models.JSONField(blank=True, null=True)),
                ('bylaws_json', models.JSONField(blank=True, null=True)),
                ('procedures_json', models.JSONField(blank=True, null=True)),
                ('related_opinions', models.ManyToManyField(blank=True, related_name='referenced_by_opinions', to='Advisory_Opinions.advisoryopinion')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('Law', 'قانون'), ('Article', 'ماده')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisory_Opinions.advisoryopinion')),
                ('to_law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laws.law')),
            ],
            options={
                'unique_together': {('from_opinion', 'to_law', 'relation_type')},
            },
        ),
        migrations.AddField(
            model_name='advisoryopinion',
            name='related_laws',
            field=models.ManyToManyField(blank=True, related_name='related_opinions', through='Advisory_Opinions.RelatedLaws', to='Laws.law'),
        ),
    ]
