# Generated by Django 6.0.4 on 2026-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisory_Opinions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisoryopinion',
            old_name='unificationRulingsACJ_json',
            new_name='unification_rulings_acj_json',
        ),
        migrations.AlterField(
            model_name='relatedlaws',
            name='relation_type',
            field=models.CharField(choices=[('Law', 'قانون'), ('Article', 'ماده'), ('Law', 'Law'), ('Agreement', 'Agreement'), ('Approval', 'Approval'), ('Bylaw', 'Bylaw'), ('Charter', 'Charter'), ('Circular', 'Circular'), ('Convention', 'Convention'), ('Instruction', 'Instruction'), ('Procedure', 'Procedure'), ('Regulation', 'Regulation'), ('Statutes', 'Statutes')], max_length=30),
        ),
    ]
