# Generated by Django 6.0.4 on 2026-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisory_Opinions', '0002_rename_unificationrulingsacj_json_advisoryopinion_unification_rulings_acj_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedlaws',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('Law', 'قانون'), ('Article', 'ماده'), ('Law', 'Law'), ('Agreement', 'Agreement'), ('Approval', 'Approval'), ('Bylaw', 'Bylaw'), ('Charter', 'Charter'), ('Circular', 'Circular'), ('Convention', 'Convention'), ('Instruction', 'Instruction'), ('Procedure', 'Procedure'), ('Regulation', 'Regulation'), ('Statutes', 'Statutes')], max_length=30, null=True),
        ),
    ]
