# Generated by Django 6.0.4 on 2026-06-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advisory_Opinions', '0003_alter_relatedlaws_relation_type'),
        ('Laws', '0011_alter_law_search_vector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedlaws',
            old_name='relation_type',
            new_name='relation_reason',
        ),
        migrations.AlterUniqueTogether(
            name='relatedlaws',
            unique_together={('from_opinion', 'to_law', 'relation_reason')},
        ),
    ]
