# Generated by Django 6.0.4 on 2026-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisory_Opinions', '0004_rename_relation_type_relatedlaws_relation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryopinion',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
