# Generated by Django 6.0.4 on 2026-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisory_Opinions', '0005_advisoryopinion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryopinion',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advisoryopinion',
            name='court_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
