services:
  django:
    build:
      context: .
    ports:
      - "7070:7070"
    volumes:
      - .:/Judicial
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:7070"
    environment:
      SECRET_KEY: 35jgrmnrgjj45904949iprjgj5n8s0l9u2z!@#$%^&*()_+
      DEBUG: true
      ALLOWED_HOSTS: "127.0.0.1"
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: postgres
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASSWORD: changeme
      DB_PORT: 5432
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    # image: postgres:16 baraye mahan koskhol
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
    ports:
      - '5430:5432'
      # - '5432:5432' baraye mahan koskhol

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      # - "6380:6379" baraye mahan koskhol

volumes:
  dev-postgres-data:
