# Generated by Django 6.0.4 on 2026-05-22 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
            ],
            options={
                'verbose_name': 'نتیجه آزمون',
                'verbose_name_plural': 'نتایج آزمون\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.quiz',),
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ\u200cهای کاربران'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'شرکت در آزمون', 'verbose_name_plural': 'شرکت\u200cهای کاربران در آزمون'},
        ),
        migrations.AlterModelOptions(
            name='quizpayment',
            options={'verbose_name': 'پرداخت آزمون', 'verbose_name_plural': 'پرداخت\u200cهای آزمون'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='شرکت در آزمون'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.option', verbose_name='پاسخ کاربر'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='ایا این گزینه صحیح است؟'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=500, verbose_name='متن گزینه'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ثبت شده در'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='آزمون فعال است؟'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ثبت شده در'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='تمام شده'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0, verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='quizleaderboard',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='quiz.quiz', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='quizleaderboard',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='quizleaderboard',
            name='score',
            field=models.FloatField(verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='quizleaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='quizpayment',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='quizpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='quizpayment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='quizpayment',
            name='payment_key',
            field=models.CharField(max_length=150, verbose_name='کد پرداخت'),
        ),
        migrations.AlterField(
            model_name='quizpayment',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='quiz.quiz', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='quizpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
