# Generated by Django 6.0.4 on 2026-05-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Law', 'قانون'), ('Article', 'ماده'), ('Note', 'تبصره')], max_length=10)),
                ('title', models.TextField(blank=True, null=True)),
                ('main_content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('short_summary', models.TextField(blank=True, null=True)),
                ('approving_authority', models.CharField(blank=True, max_length=1000, null=True)),
                ('main_source', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('scrape_source', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=700, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Law', 'Law'), ('Agreement', 'Agreement'), ('Approval', 'Approval'), ('Bylaw', 'Bylaw'), ('Charter', 'Charter'), ('Circular', 'Circular'), ('Convention', 'Convention'), ('Instruction', 'Instruction'), ('Procedure', 'Procedure'), ('Regulation', 'Regulation'), ('Statutes', 'Statutes')], default=None, max_length=20, null=True)),
                ('article_count', models.IntegerField(blank=True, null=True)),
                ('notes_count', models.IntegerField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('bylaws_json', models.JSONField(blank=True, null=True)),
                ('related_articles_json', models.JSONField(blank=True, null=True)),
                ('related_laws_json', models.JSONField(blank=True, null=True)),
                ('circulars_json', models.JSONField(blank=True, null=True)),
                ('regulations_json', models.JSONField(blank=True, null=True)),
                ('approvals_json', models.JSONField(blank=True, null=True)),
                ('procedures_json', models.JSONField(blank=True, null=True)),
                ('conventions_json', models.JSONField(blank=True, null=True)),
                ('instructions_json', models.JSONField(blank=True, null=True)),
                ('attachment_json', models.JSONField(blank=True, null=True)),
                ('keywords_json', models.JSONField(blank=True, null=True)),
                ('advisory_opinions_json', models.JSONField(blank=True, null=True)),
                ('judicial_sessions_json', models.JSONField(blank=True, null=True)),
                ('general_assembly_decisions_acj_json', models.JSONField(blank=True, null=True)),
                ('advisory_opinions_acj_json', models.JSONField(blank=True, null=True)),
                ('unification_rulings_acj_json', models.JSONField(blank=True, null=True)),
                ('specialized_boards_rulings_acj_json', models.JSONField(blank=True, null=True)),
                ('unification_rulings_sc_json', models.JSONField(blank=True, null=True)),
                ('case_laws_and_decisions_json', models.JSONField(blank=True, null=True)),
                ('breadcrumb_json', models.JSONField(blank=True, null=True)),
                ('breadcrumbIds_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Laws.law')),
            ],
        ),
        migrations.CreateModel(
            name='LawRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rel', to='Laws.law')),
                ('to_law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rel', to='Laws.law')),
            ],
            options={
                'unique_together': {('from_law', 'to_law', 'relation_type')},
            },
        ),
        migrations.AddField(
            model_name='law',
            name='related_items',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', through='Laws.LawRelationship', to='Laws.law'),
        ),
    ]
