# Generated by Django 6.0.4 on 2026-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='article_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='note_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
