# Generated by Django 6.0.4 on 2026-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0002_law_article_no_law_note_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
