# Generated by Django 6.0.4 on 2026-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0003_law_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True),
        ),
    ]
