# Generated by Django 6.0.4 on 2026-06-02 13:40

import Laws.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0004_alter_law_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='id',
            field=models.CharField(default=Laws.models.generate_objectid, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
