# Generated by Django 6.0.4 on 2026-06-09 09:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0005_alter_law_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='law',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Laws_law_search__4caf51_gin'),
        ),
    ]
