# Generated by Django 6.0.4 on 2026-06-09 12:28

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0006_law_search_vector_law_laws_law_search__4caf51_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
