# Generated by Django 6.0.4 on 2026-06-09 15:44

import Laws.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0007_alter_law_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.CharField(db_index=True, default=Laws.models.generate_objectid, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
