# Generated by Django 6.0.4 on 2026-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0008_breadcrumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='breadcrumbs',
            field=models.ManyToManyField(blank=True, null=True, related_name='laws', to='Laws.breadcrumb'),
        ),
    ]
