# Generated by Django 6.0.4 on 2026-06-09 18:14

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0010_breadcrumb_created_at_breadcrumb_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
