# Generated by Django 6.0.4 on 2026-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0011_alter_law_search_vector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lawrelationship',
            unique_together=set(),
        ),

        migrations.AddField(
            model_name='lawrelationship',
            name='relation_reason',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawrelationship',
            name='title',
            field=models.CharField(max_length=300, blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='lawrelationship',
            name='relation_type',
        ),

        migrations.AlterUniqueTogether(
            name='lawrelationship',
            unique_together={('from_law', 'to_law', 'relation_reason')},
        ),
    ]
