# Generated by Django 6.0.4 on 2026-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laws', '0012_alter_lawrelationship_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='category',
            new_name='legal_type',
        ),
    ]
